### ISSUE TITLE
failed to initialize vulnerable driver 

### ISSUE THREAD

**Issue by Nirraen** [ZZZ-Monster/HackExternal--bloodhunt#5]
ZZZ-Monster release .exe works great
But if I compile it myself, I get an error when I start up .exe:
```
[!] failed to obtain device handle (0x2)
[!] failed to initialize vulnerable driver
```
error after executing a line 94 in mhyprot.cpp 
detail::device_handle gets the value 0xffffffffffffffff 

windows 10 21h2. amd ryzen 2600x. vs 2019 v142. compiled in release x64. DirectX SDK June 2010 is installed

Am I doing something wrong because the original release from zzz-monster works.
If anyone has any ideas, please tell me.

**Comment by ZZZ-Monster** [comment]
> ZZZ-Monster release .exe works great But if I compile it myself, I get an error when I start up .exe:
> 
> ```
> [!] failed to obtain device handle (0x2)
> [!] failed to initialize vulnerable driver
> ```
> 
> error after executing a line 94 in mhyprot.cpp detail::device_handle gets the value 0xffffffffffffffff
> 
> windows 10 21h2. amd ryzen 2600x. vs 2019 v142. compiled in release x64. DirectX SDK June 2010 is installed
> 
> Am I doing something wrong because the original release from zzz-monster works. If anyone has any ideas, please tell me.

I don't know. Everything is normal here

> ZZZ-Monster release .exe works great But if I compile it myself, I get an error when I start up .exe:
> 
> ```
> [!] failed to obtain device handle (0x2)
> [!] failed to initialize vulnerable driver
> ```
> 
> error after executing a line 94 in mhyprot.cpp detail::device_handle gets the value 0xffffffffffffffff
> 
> windows 10 21h2. amd ryzen 2600x. vs 2019 v142. compiled in release x64. DirectX SDK June 2010 is installed
> 
> Am I doing something wrong because the original release from zzz-monster works. If anyone has any ideas, please tell me.

I don't know. Everything is normal here.

**Comment by Nirraen** [comment]
I get it.
if change MHYPROT_DEVICE_NAME, there will be the problems mentioned above

file: mhyprot.hpp line 41.

#define MHYPROT_DEVICE_NAME "\\\\?\\\\mhyprot2"
to example: 
#define MHYPROT_DEVICE_NAME "\\\\?\\\\MyName2222"


It's just better not to touch it if you don't know how to rename it. 
The question is solved.
